/* eslint-disable */
/**
 * Generated by Convex - this file will be overwritten when running `npx convex dev`
 * Run `npx convex dev` to connect to your Convex backend and generate proper types.
 */

import { AnyApi } from "convex/server";

export const api: AnyApi = {} as AnyApi;
export const internal: AnyApi = {} as AnyApi;
