/* eslint-disable */
/**
 * Generated by Convex - this file will be overwritten when running `npx convex dev`
 * Run `npx convex dev` to connect to your Convex backend and generate proper types.
 */

import type { GenericDataModel, GenericDocument } from "convex/server";
import type { GenericId } from "convex/values";

export type DataModel = GenericDataModel;
export type Doc<TableName extends string> = GenericDocument;
export type Id<TableName extends string> = GenericId<TableName>;
